# [START cloudbuild_npm_node]
steps:
  # Install dependencies
  - name: node
    entrypoint: npm
    args: ["install"]
  # Run tests
  - name: node
    entrypoint: npm
    args: ["test"]
  # Run custom commands
  - name: node
    entrypoint: npm
    args: ["run", "build"]
  # logging
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'your-image-name', '.']

logs_bucket: 'gs://cloud-build-logging-az'
# [END cloudbuild_npm_node]
